[Update #2] workflow (pass build result as artifact to plain machine)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,7 +17,7 @@ on:
     #   - "include/**"
 
 jobs:
-  document:
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -39,3 +39,33 @@ jobs:
       - name: Test
         working-directory: ${{github.workspace}}/build
         run: ctest
+
+      - name: Compress build result
+        run: tar czf build.tar.gz build/
+
+      - name: Upload build result as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: build_result
+          path: build.tar.gz
+
+  use_plain_env:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Download build result from artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build_result
+
+      - name: Decompress build result as artifact
+        run: tar xzf build.tar.gz
+
+      - name: Extract executable and Test
+        run: |
+          ./build/cli/invokepython_cli; result=$?
+          if [ $result -eq 0 ]; then
+            echo "Succeeded."
+          else
+            echo "Failed."
+          fi
